[package]
name = "rocket-dynamic-router"
version = "0.1.0"
authors = ["Alexandre Del Vecchio <alexandre@delvecch.io>"]
edition = "2018"

[dependencies]
rocket = "0.4.1"
notify = "4.0.0"
toml = "0.2"
rustc-serialize = "0.3.19"